/**
 * TypeScript types for Supabase database schema
 * Synced with playfunia_schema.sql + add_refunds_table.sql
 * Last updated: 2026-02-07
 *
 * Tables: 37 (all public schema tables in the live DB)
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      locations: {
        Row: {
          location_id: number;
          name: string;
          address: string | null;
          city: string | null;
          state: string | null;
          postal_code: string | null;
          phone: string | null;
          email: string | null;
          is_active: boolean | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          location_id?: number;
          name: string;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          phone?: string | null;
          email?: string | null;
          is_active?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          location_id?: number;
          name?: string;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          phone?: string | null;
          email?: string | null;
          is_active?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      store_hours: {
        Row: {
          id: number;
          location_name: string;
          day_of_week: number;
          open_time: string;
          close_time: string;
          is_closed: boolean | null;
          is_active: boolean | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: number;
          location_name: string;
          day_of_week: number;
          open_time: string;
          close_time: string;
          is_closed?: boolean | null;
          is_active?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: number;
          location_name?: string;
          day_of_week?: number;
          open_time?: string;
          close_time?: string;
          is_closed?: boolean | null;
          is_active?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      customers: {
        Row: {
          customer_id: number;
          full_name: string;
          email: string | null;
          phone: string | null;
          address: string | null;
          notes: string | null;
          is_guest: boolean | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          customer_id?: number;
          full_name: string;
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          notes?: string | null;
          is_guest?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          customer_id?: number;
          full_name?: string;
          email?: string | null;
          phone?: string | null;
          address?: string | null;
          notes?: string | null;
          is_guest?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      ticket_types: {
        Row: {
          ticket_type_id: number;
          name: string;
          description: string | null;
          base_price_usd: number;
          child_count: number | null;
          requires_waiver: boolean | null;
          requires_grip_socks: boolean | null;
          is_active: boolean | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          ticket_type_id?: number;
          name: string;
          description?: string | null;
          base_price_usd: number;
          child_count?: number | null;
          requires_waiver?: boolean | null;
          requires_grip_socks?: boolean | null;
          is_active?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          ticket_type_id?: number;
          name?: string;
          description?: string | null;
          base_price_usd?: number;
          child_count?: number | null;
          requires_waiver?: boolean | null;
          requires_grip_socks?: boolean | null;
          is_active?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      party_packages: {
        Row: {
          package_id: number;
          name: string;
          description: string | null;
          price_usd: number;
          base_children: number;
          base_room_hours: number;
          includes_food: boolean | null;
          includes_drinks: boolean | null;
          includes_decor: boolean | null;
          features: Json | null;
          additional_terms: Json | null;
          extra_child_price: number | null;
          extra_adult_price: number | null;
          cleaning_fee: number | null;
          is_active: boolean | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          package_id?: number;
          name: string;
          description?: string | null;
          price_usd: number;
          base_children?: number;
          base_room_hours?: number;
          includes_food?: boolean | null;
          includes_drinks?: boolean | null;
          includes_decor?: boolean | null;
          features?: Json | null;
          additional_terms?: Json | null;
          extra_child_price?: number | null;
          extra_adult_price?: number | null;
          cleaning_fee?: number | null;
          is_active?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          package_id?: number;
          name?: string;
          description?: string | null;
          price_usd?: number;
          base_children?: number;
          base_room_hours?: number;
          includes_food?: boolean | null;
          includes_drinks?: boolean | null;
          includes_decor?: boolean | null;
          features?: Json | null;
          additional_terms?: Json | null;
          extra_child_price?: number | null;
          extra_adult_price?: number | null;
          cleaning_fee?: number | null;
          is_active?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      party_add_ons: {
        Row: {
          add_on_id: number;
          code: string;
          label: string;
          description: string | null;
          price: number;
          price_type: string;
          is_active: boolean | null;
          display_order: number | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          add_on_id?: number;
          code: string;
          label: string;
          description?: string | null;
          price: number;
          price_type?: string;
          is_active?: boolean | null;
          display_order?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          add_on_id?: number;
          code?: string;
          label?: string;
          description?: string | null;
          price?: number;
          price_type?: string;
          is_active?: boolean | null;
          display_order?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      pricing_config: {
        Row: {
          config_id: number;
          config_key: string;
          config_value: number;
          description: string | null;
          is_active: boolean | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          config_id?: number;
          config_key: string;
          config_value: number;
          description?: string | null;
          is_active?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          config_id?: number;
          config_key?: string;
          config_value?: number;
          description?: string | null;
          is_active?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      resources: {
        Row: {
          resource_id: number;
          location_id: number;
          name: string;
          type: string;
          capacity: number | null;
          is_active: boolean | null;
          created_at: string | null;
        };
        Insert: {
          resource_id?: number;
          location_id: number;
          name: string;
          type?: string;
          capacity?: number | null;
          is_active?: boolean | null;
          created_at?: string | null;
        };
        Update: {
          resource_id?: number;
          location_id?: number;
          name?: string;
          type?: string;
          capacity?: number | null;
          is_active?: boolean | null;
          created_at?: string | null;
        };
      };
      faqs: {
        Row: {
          faq_id: number;
          question: string;
          answer: string;
          is_active: boolean | null;
          category: string | null;
          display_order: number | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          faq_id?: number;
          question: string;
          answer: string;
          is_active?: boolean | null;
          category?: string | null;
          display_order?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          faq_id?: number;
          question?: string;
          answer?: string;
          is_active?: boolean | null;
          category?: string | null;
          display_order?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      testimonials: {
        Row: {
          testimonial_id: number;
          name: string;
          quote: string;
          rating: number | null;
          is_featured: boolean | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          testimonial_id?: number;
          name: string;
          quote: string;
          rating?: number | null;
          is_featured?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          testimonial_id?: number;
          name?: string;
          quote?: string;
          rating?: number | null;
          is_featured?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      announcements: {
        Row: {
          announcement_id: number;
          title: string;
          body: string;
          publish_date: string | null;
          expires_at: string | null;
          is_active: boolean;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          announcement_id?: number;
          title: string;
          body: string;
          publish_date?: string | null;
          expires_at?: string | null;
          is_active?: boolean;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          announcement_id?: number;
          title?: string;
          body?: string;
          publish_date?: string | null;
          expires_at?: string | null;
          is_active?: boolean;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      promotions: {
        Row: {
          promotion_id: number;
          code: string;
          description: string | null;
          percent_off: number | null;
          amount_off_usd: number | null;
          valid_from: string | null;
          valid_to: string | null;
          max_redemptions: number | null;
          redemptions: number | null;
          is_active: boolean | null;
          created_at: string | null;
        };
        Insert: {
          promotion_id?: number;
          code: string;
          description?: string | null;
          percent_off?: number | null;
          amount_off_usd?: number | null;
          valid_from?: string | null;
          valid_to?: string | null;
          max_redemptions?: number | null;
          redemptions?: number | null;
          is_active?: boolean | null;
          created_at?: string | null;
        };
        Update: {
          promotion_id?: number;
          code?: string;
          description?: string | null;
          percent_off?: number | null;
          amount_off_usd?: number | null;
          valid_from?: string | null;
          valid_to?: string | null;
          max_redemptions?: number | null;
          redemptions?: number | null;
          is_active?: boolean | null;
          created_at?: string | null;
        };
      };
      users: {
        Row: {
          user_id: number;
          email: string;
          password_hash: string | null;
          auth_user_id: string | null;
          first_name: string | null;
          last_name: string | null;
          phone: string | null;
          roles: string[];
          customer_id: number | null;
          address_line1: string | null;
          address_line2: string | null;
          address_city: string | null;
          address_state: string | null;
          address_postal_code: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          user_id?: number;
          email: string;
          password_hash?: string | null;
          auth_user_id?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          phone?: string | null;
          roles?: string[];
          customer_id?: number | null;
          address_line1?: string | null;
          address_line2?: string | null;
          address_city?: string | null;
          address_state?: string | null;
          address_postal_code?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          user_id?: number;
          email?: string;
          password_hash?: string | null;
          auth_user_id?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          phone?: string | null;
          roles?: string[];
          customer_id?: number | null;
          address_line1?: string | null;
          address_line2?: string | null;
          address_city?: string | null;
          address_state?: string | null;
          address_postal_code?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      children: {
        Row: {
          child_id: number;
          customer_id: number;
          first_name: string;
          last_name: string | null;
          birth_date: string | null;
          gender: string | null;
          allergies: string | null;
          notes: string | null;
          membership_tier: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          child_id?: number;
          customer_id: number;
          first_name: string;
          last_name?: string | null;
          birth_date?: string | null;
          gender?: string | null;
          allergies?: string | null;
          notes?: string | null;
          membership_tier?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          child_id?: number;
          customer_id?: number;
          first_name?: string;
          last_name?: string | null;
          birth_date?: string | null;
          gender?: string | null;
          allergies?: string | null;
          notes?: string | null;
          membership_tier?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      events: {
        Row: {
          event_id: number;
          title: string;
          description: string | null;
          start_date: string;
          end_date: string;
          image_url: string | null;
          is_published: boolean | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          event_id?: number;
          title: string;
          description?: string | null;
          start_date: string;
          end_date: string;
          image_url?: string | null;
          is_published?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          event_id?: number;
          title?: string;
          description?: string | null;
          start_date?: string;
          end_date?: string;
          image_url?: string | null;
          is_published?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      membership_plans: {
        Row: {
          plan_id: number;
          name: string;
          description: string | null;
          monthly_price: number;
          benefits: string[] | null;
          max_children: number | null;
          visits_per_month: number | null;
          discount_percent: number | null;
          guest_passes_per_month: number | null;
          is_active: boolean | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          plan_id?: number;
          name: string;
          description?: string | null;
          monthly_price: number;
          benefits?: string[] | null;
          max_children?: number | null;
          visits_per_month?: number | null;
          discount_percent?: number | null;
          guest_passes_per_month?: number | null;
          is_active?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          plan_id?: number;
          name?: string;
          description?: string | null;
          monthly_price?: number;
          benefits?: string[] | null;
          max_children?: number | null;
          visits_per_month?: number | null;
          discount_percent?: number | null;
          guest_passes_per_month?: number | null;
          is_active?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      memberships: {
        Row: {
          membership_id: number;
          customer_id: number;
          plan_id: number | null;
          tier: string;
          status: string;
          start_date: string;
          end_date: string | null;
          auto_renew: boolean | null;
          visits_per_month: number | null;
          visits_used_this_period: number | null;
          visit_period_start: string | null;
          last_visit_at: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          membership_id?: number;
          customer_id: number;
          plan_id?: number | null;
          tier: string;
          status?: string;
          start_date: string;
          end_date?: string | null;
          auto_renew?: boolean | null;
          visits_per_month?: number | null;
          visits_used_this_period?: number | null;
          visit_period_start?: string | null;
          last_visit_at?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          membership_id?: number;
          customer_id?: number;
          plan_id?: number | null;
          tier?: string;
          status?: string;
          start_date?: string;
          end_date?: string | null;
          auto_renew?: boolean | null;
          visits_per_month?: number | null;
          visits_used_this_period?: number | null;
          visit_period_start?: string | null;
          last_visit_at?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      membership_reminders: {
        Row: {
          reminder_id: number;
          membership_id: number;
          reminder_type: string;
          sent_at: string;
          notification_method: string;
          status: string;
          error_message: string | null;
          created_at: string | null;
        };
        Insert: {
          reminder_id?: number;
          membership_id: number;
          reminder_type: string;
          sent_at?: string;
          notification_method: string;
          status?: string;
          error_message?: string | null;
          created_at?: string | null;
        };
        Update: {
          reminder_id?: number;
          membership_id?: number;
          reminder_type?: string;
          sent_at?: string;
          notification_method?: string;
          status?: string;
          error_message?: string | null;
          created_at?: string | null;
        };
      };
      orders: {
        Row: {
          order_id: number;
          customer_id: number | null;
          location_id: number | null;
          order_type: string;
          status: string;
          subtotal_usd: number;
          discount_usd: number;
          tax_usd: number;
          total_usd: number;
          notes: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          order_id?: number;
          customer_id?: number | null;
          location_id?: number | null;
          order_type?: string;
          status?: string;
          subtotal_usd?: number;
          discount_usd?: number;
          tax_usd?: number;
          total_usd?: number;
          notes?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          order_id?: number;
          customer_id?: number | null;
          location_id?: number | null;
          order_type?: string;
          status?: string;
          subtotal_usd?: number;
          discount_usd?: number;
          tax_usd?: number;
          total_usd?: number;
          notes?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      party_bookings: {
        Row: {
          booking_id: number;
          customer_id: number | null;
          package_id: number;
          reference: string | null;
          event_date: string | null;
          start_time: string | null;
          end_time: string | null;
          scheduled_start: string | null;
          scheduled_end: string | null;
          location_name: string | null;
          guests: number | null;
          notes: string | null;
          add_ons: Json | null;
          subtotal: number | null;
          cleaning_fee: number | null;
          total: number | null;
          deposit_amount: number | null;
          balance_remaining: number | null;
          status: string | null;
          payment_status: string | null;
          deposit_paid_at: string | null;
          latest_payment_id: string | null;
          child_ids: number[] | null;
          private_notes: string | null;
          payment_option: string | null;
          guest_name: string | null;
          guest_email: string | null;
          guest_phone: string | null;
          online_payment_amount: number | null;
          venue_payment_amount: number | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          booking_id?: number;
          customer_id?: number | null;
          package_id: number;
          reference?: string | null;
          event_date?: string | null;
          start_time?: string | null;
          end_time?: string | null;
          scheduled_start?: string | null;
          scheduled_end?: string | null;
          location_name?: string | null;
          guests?: number | null;
          notes?: string | null;
          add_ons?: Json | null;
          subtotal?: number | null;
          cleaning_fee?: number | null;
          total?: number | null;
          deposit_amount?: number | null;
          balance_remaining?: number | null;
          status?: string | null;
          payment_status?: string | null;
          deposit_paid_at?: string | null;
          latest_payment_id?: string | null;
          child_ids?: number[] | null;
          private_notes?: string | null;
          payment_option?: string | null;
          guest_name?: string | null;
          guest_email?: string | null;
          guest_phone?: string | null;
          online_payment_amount?: number | null;
          venue_payment_amount?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          booking_id?: number;
          customer_id?: number | null;
          package_id?: number;
          reference?: string | null;
          event_date?: string | null;
          start_time?: string | null;
          end_time?: string | null;
          scheduled_start?: string | null;
          scheduled_end?: string | null;
          location_name?: string | null;
          guests?: number | null;
          notes?: string | null;
          add_ons?: Json | null;
          subtotal?: number | null;
          cleaning_fee?: number | null;
          total?: number | null;
          deposit_amount?: number | null;
          balance_remaining?: number | null;
          status?: string | null;
          payment_status?: string | null;
          deposit_paid_at?: string | null;
          latest_payment_id?: string | null;
          child_ids?: number[] | null;
          private_notes?: string | null;
          payment_option?: string | null;
          guest_name?: string | null;
          guest_email?: string | null;
          guest_phone?: string | null;
          online_payment_amount?: number | null;
          venue_payment_amount?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      order_items: {
        Row: {
          order_item_id: number;
          order_id: number;
          item_type: string;
          product_id: number | null;
          ticket_type_id: number | null;
          booking_id: number | null;
          event_id: number | null;
          name_override: string | null;
          quantity: number;
          unit_price_usd: number;
          line_total_usd: number;
        };
        Insert: {
          order_item_id?: number;
          order_id: number;
          item_type: string;
          product_id?: number | null;
          ticket_type_id?: number | null;
          booking_id?: number | null;
          event_id?: number | null;
          name_override?: string | null;
          quantity: number;
          unit_price_usd: number;
          line_total_usd: number;
        };
        Update: {
          order_item_id?: number;
          order_id?: number;
          item_type?: string;
          product_id?: number | null;
          ticket_type_id?: number | null;
          booking_id?: number | null;
          event_id?: number | null;
          name_override?: string | null;
          quantity?: number;
          unit_price_usd?: number;
          line_total_usd?: number;
        };
      };
      payments: {
        Row: {
          payment_id: number;
          order_id: number;
          provider: string;
          provider_payment_id: string | null;
          status: string;
          amount_usd: number;
          receipt_url: string | null;
          created_at: string | null;
        };
        Insert: {
          payment_id?: number;
          order_id: number;
          provider: string;
          provider_payment_id?: string | null;
          status?: string;
          amount_usd: number;
          receipt_url?: string | null;
          created_at?: string | null;
        };
        Update: {
          payment_id?: number;
          order_id?: number;
          provider?: string;
          provider_payment_id?: string | null;
          status?: string;
          amount_usd?: number;
          receipt_url?: string | null;
          created_at?: string | null;
        };
      };
      waiver_users: {
        Row: {
          waiver_user_id: number;
          guardian_first_name: string;
          guardian_last_name: string;
          guardian_date_of_birth: string | null;
          guardian_phone: string | null;
          guardian_email: string | null;
          relationship_to_minor: string | null;
          marketing_opt_in: boolean;
          last_waiver_signed_at: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          waiver_user_id?: number;
          guardian_first_name: string;
          guardian_last_name?: string;
          guardian_date_of_birth?: string | null;
          guardian_phone?: string | null;
          guardian_email?: string | null;
          relationship_to_minor?: string | null;
          marketing_opt_in?: boolean;
          last_waiver_signed_at?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          waiver_user_id?: number;
          guardian_first_name?: string;
          guardian_last_name?: string;
          guardian_date_of_birth?: string | null;
          guardian_phone?: string | null;
          guardian_email?: string | null;
          relationship_to_minor?: string | null;
          marketing_opt_in?: boolean;
          last_waiver_signed_at?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      waiver_user_children: {
        Row: {
          waiver_user_child_id: number;
          waiver_user_id: number;
          minor_first_name: string;
          minor_last_name: string | null;
          minor_date_of_birth: string;
          minor_gender: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          waiver_user_child_id?: number;
          waiver_user_id: number;
          minor_first_name: string;
          minor_last_name?: string | null;
          minor_date_of_birth: string;
          minor_gender?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          waiver_user_child_id?: number;
          waiver_user_id?: number;
          minor_first_name?: string;
          minor_last_name?: string | null;
          minor_date_of_birth?: string;
          minor_gender?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      waiver_submissions: {
        Row: {
          submission_id: number;
          customer_id: number | null;
          waiver_user_id: number | null;
          guardian_first_name: string;
          guardian_last_name: string;
          guardian_date_of_birth: string | null;
          guardian_phone: string | null;
          guardian_email: string | null;
          relationship_to_minor: string | null;
          child_ids: number[] | null;
          digital_signature: string;
          waiver_agreement_accepted: boolean;
          accepted_policies: string[];
          marketing_sms_opt_in: boolean | null;
          marketing_email_opt_in: boolean | null;
          date_signed: string;
          expires_at: string | null;
          archive_until: string | null;
          ip_address: string | null;
          waiver_code: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          submission_id?: number;
          customer_id?: number | null;
          waiver_user_id?: number | null;
          guardian_first_name: string;
          guardian_last_name?: string;
          guardian_date_of_birth?: string | null;
          guardian_phone?: string | null;
          guardian_email?: string | null;
          relationship_to_minor?: string | null;
          child_ids?: number[] | null;
          digital_signature: string;
          waiver_agreement_accepted?: boolean;
          accepted_policies: string[];
          marketing_sms_opt_in?: boolean | null;
          marketing_email_opt_in?: boolean | null;
          date_signed?: string;
          expires_at?: string | null;
          archive_until?: string | null;
          ip_address?: string | null;
          waiver_code?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          submission_id?: number;
          customer_id?: number | null;
          waiver_user_id?: number | null;
          guardian_first_name?: string;
          guardian_last_name?: string;
          guardian_date_of_birth?: string | null;
          guardian_phone?: string | null;
          guardian_email?: string | null;
          relationship_to_minor?: string | null;
          child_ids?: number[] | null;
          digital_signature?: string;
          waiver_agreement_accepted?: boolean;
          accepted_policies?: string[];
          marketing_sms_opt_in?: boolean | null;
          marketing_email_opt_in?: boolean | null;
          date_signed?: string;
          expires_at?: string | null;
          archive_until?: string | null;
          ip_address?: string | null;
          waiver_code?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      waiver_visits: {
        Row: {
          visit_id: number;
          waiver_user_id: number;
          waiver_submission_id: number | null;
          visited_at: string;
          created_at: string | null;
        };
        Insert: {
          visit_id?: number;
          waiver_user_id: number;
          waiver_submission_id?: number | null;
          visited_at?: string;
          created_at?: string | null;
        };
        Update: {
          visit_id?: number;
          waiver_user_id?: number;
          waiver_submission_id?: number | null;
          visited_at?: string;
          created_at?: string | null;
        };
      };
      ticket_purchases: {
        Row: {
          purchase_id: number;
          customer_id: number;
          ticket_type_id: number | null;
          event_id: number | null;
          ticket_type: string;
          quantity: number;
          unit_price: number;
          total: number;
          codes: Json;
          status: string;
          metadata: Json | null;
          provider_payment_id: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          purchase_id?: number;
          customer_id: number;
          ticket_type_id?: number | null;
          event_id?: number | null;
          ticket_type?: string;
          quantity?: number;
          unit_price: number;
          total: number;
          codes?: Json;
          status?: string;
          metadata?: Json | null;
          provider_payment_id?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          purchase_id?: number;
          customer_id?: number;
          ticket_type_id?: number | null;
          event_id?: number | null;
          ticket_type?: string;
          quantity?: number;
          unit_price?: number;
          total?: number;
          codes?: Json;
          status?: string;
          metadata?: Json | null;
          provider_payment_id?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      app_payments: {
        Row: {
          app_payment_id: number;
          customer_id: number;
          amount: number;
          currency: string;
          status: string;
          provider_payment_id: string;
          purpose: string;
          metadata: Json | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          app_payment_id?: number;
          customer_id: number;
          amount: number;
          currency?: string;
          status?: string;
          provider_payment_id: string;
          purpose: string;
          metadata?: Json | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          app_payment_id?: number;
          customer_id?: number;
          amount?: number;
          currency?: string;
          status?: string;
          provider_payment_id?: string;
          purpose?: string;
          metadata?: Json | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      email_otps: {
        Row: {
          id: number;
          email: string;
          otp_code: string;
          otp_type: string;
          expires_at: string;
          verified_at: string | null;
          registration_data: Json | null;
          created_at: string | null;
        };
        Insert: {
          id?: number;
          email: string;
          otp_code: string;
          otp_type?: string;
          expires_at: string;
          verified_at?: string | null;
          registration_data?: Json | null;
          created_at?: string | null;
        };
        Update: {
          id?: number;
          email?: string;
          otp_code?: string;
          otp_type?: string;
          expires_at?: string;
          verified_at?: string | null;
          registration_data?: Json | null;
          created_at?: string | null;
        };
      };
      receipts: {
        Row: {
          receipt_id: number;
          receipt_number: string;
          customer_id: number | null;
          purchase_type: string;
          reference_id: number;
          subtotal_usd: number;
          discount_usd: number;
          tax_usd: number;
          total_usd: number;
          payment_method: string | null;
          payment_id: string | null;
          verification_hash: string;
          metadata: Json | null;
          created_at: string | null;
        };
        Insert: {
          receipt_id?: number;
          receipt_number: string;
          customer_id?: number | null;
          purchase_type: string;
          reference_id: number;
          subtotal_usd: number;
          discount_usd?: number;
          tax_usd?: number;
          total_usd: number;
          payment_method?: string | null;
          payment_id?: string | null;
          verification_hash: string;
          metadata?: Json | null;
          created_at?: string | null;
        };
        Update: {
          receipt_id?: number;
          receipt_number?: string;
          customer_id?: number | null;
          purchase_type?: string;
          reference_id?: number;
          subtotal_usd?: number;
          discount_usd?: number;
          tax_usd?: number;
          total_usd?: number;
          payment_method?: string | null;
          payment_id?: string | null;
          verification_hash?: string;
          metadata?: Json | null;
          created_at?: string | null;
        };
      };
      payment_logs: {
        Row: {
          log_id: number;
          idempotency_key: string;
          payment_id: string | null;
          order_id: string | null;
          customer_id: number | null;
          user_id: number | null;
          booking_id: number | null;
          provider: string;
          payment_type: string;
          amount_usd: number;
          currency: string | null;
          status: string;
          previous_status: string | null;
          source_type: string | null;
          location_id: string | null;
          reference_id: string | null;
          response_code: string | null;
          error_category: string | null;
          error_code: string | null;
          error_detail: string | null;
          error_field: string | null;
          square_receipt_number: string | null;
          square_receipt_url: string | null;
          card_brand: string | null;
          card_last4: string | null;
          card_exp_month: number | null;
          card_exp_year: number | null;
          entry_method: string | null;
          cvv_status: string | null;
          avs_status: string | null;
          risk_level: string | null;
          risk_score: number | null;
          verification_method: string | null;
          processing_time_ms: number | null;
          request_payload: Json | null;
          response_payload: Json | null;
          ip_address: string | null;
          user_agent: string | null;
          session_id: string | null;
          metadata: Json | null;
          initiated_at: string | null;
          completed_at: string | null;
          created_at: string | null;
        };
        Insert: {
          log_id?: number;
          idempotency_key: string;
          payment_id?: string | null;
          order_id?: string | null;
          customer_id?: number | null;
          user_id?: number | null;
          booking_id?: number | null;
          provider?: string;
          payment_type: string;
          amount_usd: number;
          currency?: string | null;
          status: string;
          previous_status?: string | null;
          source_type?: string | null;
          location_id?: string | null;
          reference_id?: string | null;
          response_code?: string | null;
          error_category?: string | null;
          error_code?: string | null;
          error_detail?: string | null;
          error_field?: string | null;
          square_receipt_number?: string | null;
          square_receipt_url?: string | null;
          card_brand?: string | null;
          card_last4?: string | null;
          card_exp_month?: number | null;
          card_exp_year?: number | null;
          entry_method?: string | null;
          cvv_status?: string | null;
          avs_status?: string | null;
          risk_level?: string | null;
          risk_score?: number | null;
          verification_method?: string | null;
          processing_time_ms?: number | null;
          request_payload?: Json | null;
          response_payload?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          session_id?: string | null;
          metadata?: Json | null;
          initiated_at?: string | null;
          completed_at?: string | null;
          created_at?: string | null;
        };
        Update: {
          log_id?: number;
          idempotency_key?: string;
          payment_id?: string | null;
          order_id?: string | null;
          customer_id?: number | null;
          user_id?: number | null;
          booking_id?: number | null;
          provider?: string;
          payment_type?: string;
          amount_usd?: number;
          currency?: string | null;
          status?: string;
          previous_status?: string | null;
          source_type?: string | null;
          location_id?: string | null;
          reference_id?: string | null;
          response_code?: string | null;
          error_category?: string | null;
          error_code?: string | null;
          error_detail?: string | null;
          error_field?: string | null;
          square_receipt_number?: string | null;
          square_receipt_url?: string | null;
          card_brand?: string | null;
          card_last4?: string | null;
          card_exp_month?: number | null;
          card_exp_year?: number | null;
          entry_method?: string | null;
          cvv_status?: string | null;
          avs_status?: string | null;
          risk_level?: string | null;
          risk_score?: number | null;
          verification_method?: string | null;
          processing_time_ms?: number | null;
          request_payload?: Json | null;
          response_payload?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          session_id?: string | null;
          metadata?: Json | null;
          initiated_at?: string | null;
          completed_at?: string | null;
          created_at?: string | null;
        };
      };
      slot_reservations: {
        Row: {
          id: string;
          slot_date: string;
          slot_time: string;
          location_name: string;
          user_id: number | null;
          session_id: string;
          status: string;
          expires_at: string;
          created_at: string | null;
          confirmed_at: string | null;
          booking_id: number | null;
        };
        Insert: {
          id?: string;
          slot_date: string;
          slot_time: string;
          location_name: string;
          user_id?: number | null;
          session_id: string;
          status?: string;
          expires_at: string;
          created_at?: string | null;
          confirmed_at?: string | null;
          booking_id?: number | null;
        };
        Update: {
          id?: string;
          slot_date?: string;
          slot_time?: string;
          location_name?: string;
          user_id?: number | null;
          session_id?: string;
          status?: string;
          expires_at?: string;
          created_at?: string | null;
          confirmed_at?: string | null;
          booking_id?: number | null;
        };
      };
      webhook_events: {
        Row: {
          id: number;
          event_id: string;
          event_type: string;
          payload: Json;
          status: string;
          error_message: string | null;
          retry_count: number | null;
          created_at: string | null;
          processed_at: string | null;
        };
        Insert: {
          id?: number;
          event_id: string;
          event_type: string;
          payload: Json;
          status?: string;
          error_message?: string | null;
          retry_count?: number | null;
          created_at?: string | null;
          processed_at?: string | null;
        };
        Update: {
          id?: number;
          event_id?: string;
          event_type?: string;
          payload?: Json;
          status?: string;
          error_message?: string | null;
          retry_count?: number | null;
          created_at?: string | null;
          processed_at?: string | null;
        };
      };
      notification_queue: {
        Row: {
          id: number;
          type: string;
          recipient: string;
          subject: string | null;
          template: string;
          payload: Json;
          status: string;
          attempts: number | null;
          max_attempts: number | null;
          next_attempt_at: string | null;
          sent_at: string | null;
          last_error: string | null;
          created_at: string | null;
          reference_type: string | null;
          reference_id: number | null;
        };
        Insert: {
          id?: number;
          type: string;
          recipient: string;
          subject?: string | null;
          template: string;
          payload: Json;
          status?: string;
          attempts?: number | null;
          max_attempts?: number | null;
          next_attempt_at?: string | null;
          sent_at?: string | null;
          last_error?: string | null;
          created_at?: string | null;
          reference_type?: string | null;
          reference_id?: number | null;
        };
        Update: {
          id?: number;
          type?: string;
          recipient?: string;
          subject?: string | null;
          template?: string;
          payload?: Json;
          status?: string;
          attempts?: number | null;
          max_attempts?: number | null;
          next_attempt_at?: string | null;
          sent_at?: string | null;
          last_error?: string | null;
          created_at?: string | null;
          reference_type?: string | null;
          reference_id?: number | null;
        };
      };
      refunds: {
        Row: {
          refund_id: number;
          square_refund_id: string | null;
          square_payment_id: string;
          order_id: number | null;
          payment_id: number | null;
          booking_id: number | null;
          amount_cents: number;
          currency: string;
          status: string;
          reason: string | null;
          initiated_by: number | null;
          idempotency_key: string;
          created_at: string | null;
          processed_at: string | null;
          error_code: string | null;
          error_message: string | null;
        };
        Insert: {
          refund_id?: number;
          square_refund_id?: string | null;
          square_payment_id: string;
          order_id?: number | null;
          payment_id?: number | null;
          booking_id?: number | null;
          amount_cents: number;
          currency?: string;
          status?: string;
          reason?: string | null;
          initiated_by?: number | null;
          idempotency_key: string;
          created_at?: string | null;
          processed_at?: string | null;
          error_code?: string | null;
          error_message?: string | null;
        };
        Update: {
          refund_id?: number;
          square_refund_id?: string | null;
          square_payment_id?: string;
          order_id?: number | null;
          payment_id?: number | null;
          booking_id?: number | null;
          amount_cents?: number;
          currency?: string;
          status?: string;
          reason?: string | null;
          initiated_by?: number | null;
          idempotency_key?: string;
          created_at?: string | null;
          processed_at?: string | null;
          error_code?: string | null;
          error_message?: string | null;
        };
      };
      job_listings: {
        Row: {
          listing_id: number;
          title: string;
          slug: string;
          department: string;
          employment_type: string;
          location: string;
          description: string;
          responsibilities: string[] | null;
          qualifications: string[] | null;
          nice_to_have: string[] | null;
          perks: string[] | null;
          pay_range: string | null;
          minimum_age: number | null;
          schedule_notes: string | null;
          display_order: number | null;
          is_active: boolean | null;
          published_at: string | null;
          closes_at: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          listing_id?: number;
          title: string;
          slug: string;
          department: string;
          employment_type: string;
          location?: string;
          description: string;
          responsibilities?: string[] | null;
          qualifications?: string[] | null;
          nice_to_have?: string[] | null;
          perks?: string[] | null;
          pay_range?: string | null;
          minimum_age?: number | null;
          schedule_notes?: string | null;
          display_order?: number | null;
          is_active?: boolean | null;
          published_at?: string | null;
          closes_at?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          listing_id?: number;
          title?: string;
          slug?: string;
          department?: string;
          employment_type?: string;
          location?: string;
          description?: string;
          responsibilities?: string[] | null;
          qualifications?: string[] | null;
          nice_to_have?: string[] | null;
          perks?: string[] | null;
          pay_range?: string | null;
          minimum_age?: number | null;
          schedule_notes?: string | null;
          display_order?: number | null;
          is_active?: boolean | null;
          published_at?: string | null;
          closes_at?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      job_applications: {
        Row: {
          application_id: number;
          listing_id: number;
          first_name: string;
          last_name: string;
          email: string;
          phone: string;
          date_of_birth: string | null;
          resume_storage_path: string | null;
          resume_original_name: string | null;
          resume_mime_type: string | null;
          resume_size_bytes: number | null;
          cover_letter: string | null;
          schedule_preference: string | null;
          available_start_date: string | null;
          has_experience_with_children: boolean | null;
          how_heard: string | null;
          emergency_contact_name: string | null;
          emergency_contact_phone: string | null;
          status: string | null;
          admin_notes: string | null;
          ip_address: string | null;
          video_url: string | null;
          video_storage_path: string | null;
          video_original_name: string | null;
          video_mime_type: string | null;
          video_size_bytes: number | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          application_id?: number;
          listing_id: number;
          first_name: string;
          last_name: string;
          email: string;
          phone: string;
          date_of_birth?: string | null;
          resume_storage_path?: string | null;
          resume_original_name?: string | null;
          resume_mime_type?: string | null;
          resume_size_bytes?: number | null;
          cover_letter?: string | null;
          schedule_preference?: string | null;
          available_start_date?: string | null;
          has_experience_with_children?: boolean | null;
          how_heard?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          status?: string | null;
          admin_notes?: string | null;
          ip_address?: string | null;
          video_url?: string | null;
          video_storage_path?: string | null;
          video_original_name?: string | null;
          video_mime_type?: string | null;
          video_size_bytes?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          application_id?: number;
          listing_id?: number;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string;
          date_of_birth?: string | null;
          resume_storage_path?: string | null;
          resume_original_name?: string | null;
          resume_mime_type?: string | null;
          resume_size_bytes?: number | null;
          cover_letter?: string | null;
          schedule_preference?: string | null;
          available_start_date?: string | null;
          has_experience_with_children?: boolean | null;
          how_heard?: string | null;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          status?: string | null;
          admin_notes?: string | null;
          ip_address?: string | null;
          video_url?: string | null;
          video_storage_path?: string | null;
          video_original_name?: string | null;
          video_mime_type?: string | null;
          video_size_bytes?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      event_photos: {
        Row: {
          photo_id: number;
          event_id: number;
          photo_url: string;
          storage_path: string;
          caption: string | null;
          display_order: number | null;
          created_at: string | null;
        };
        Insert: {
          photo_id?: number;
          event_id: number;
          photo_url: string;
          storage_path: string;
          caption?: string | null;
          display_order?: number | null;
          created_at?: string | null;
        };
        Update: {
          photo_id?: number;
          event_id?: number;
          photo_url?: string;
          storage_path?: string;
          caption?: string | null;
          display_order?: number | null;
          created_at?: string | null;
        };
      };
    };
  };
}

// ============= Row types (most commonly used) =============
export type Location = Database['public']['Tables']['locations']['Row'];
export type StoreHoursRow = Database['public']['Tables']['store_hours']['Row'];
export type Customer = Database['public']['Tables']['customers']['Row'];
export type TicketType = Database['public']['Tables']['ticket_types']['Row'];
export type PartyPackage = Database['public']['Tables']['party_packages']['Row'];
export type PartyAddOn = Database['public']['Tables']['party_add_ons']['Row'];
export type PricingConfig = Database['public']['Tables']['pricing_config']['Row'];
export type Resource = Database['public']['Tables']['resources']['Row'];
export type FAQ = Database['public']['Tables']['faqs']['Row'];
export type Testimonial = Database['public']['Tables']['testimonials']['Row'];
export type Announcement = Database['public']['Tables']['announcements']['Row'];
export type Promotion = Database['public']['Tables']['promotions']['Row'];
export type User = Database['public']['Tables']['users']['Row'];
export type Child = Database['public']['Tables']['children']['Row'];
export type Event = Database['public']['Tables']['events']['Row'];
export type MembershipPlan = Database['public']['Tables']['membership_plans']['Row'];
export type Membership = Database['public']['Tables']['memberships']['Row'];
export type MembershipReminder = Database['public']['Tables']['membership_reminders']['Row'];
export type Order = Database['public']['Tables']['orders']['Row'];
export type PartyBooking = Database['public']['Tables']['party_bookings']['Row'];
export type OrderItem = Database['public']['Tables']['order_items']['Row'];
export type Payment = Database['public']['Tables']['payments']['Row'];
export type WaiverUser = Database['public']['Tables']['waiver_users']['Row'];
export type WaiverUserChild = Database['public']['Tables']['waiver_user_children']['Row'];
export type WaiverSubmission = Database['public']['Tables']['waiver_submissions']['Row'];
export type WaiverVisit = Database['public']['Tables']['waiver_visits']['Row'];
export type TicketPurchase = Database['public']['Tables']['ticket_purchases']['Row'];
export type AppPayment = Database['public']['Tables']['app_payments']['Row'];
export type EmailOtp = Database['public']['Tables']['email_otps']['Row'];
export type ReceiptRow = Database['public']['Tables']['receipts']['Row'];
export type PaymentLogRow = Database['public']['Tables']['payment_logs']['Row'];
export type SlotReservation = Database['public']['Tables']['slot_reservations']['Row'];
export type WebhookEvent = Database['public']['Tables']['webhook_events']['Row'];
export type NotificationQueueRow = Database['public']['Tables']['notification_queue']['Row'];
export type Refund = Database['public']['Tables']['refunds']['Row'];
export type JobListing = Database['public']['Tables']['job_listings']['Row'];
export type JobApplication = Database['public']['Tables']['job_applications']['Row'];
export type EventPhoto = Database['public']['Tables']['event_photos']['Row'];

// ============= Insert types =============
export type UserInsert = Database['public']['Tables']['users']['Insert'];
export type CustomerInsert = Database['public']['Tables']['customers']['Insert'];
export type ChildInsert = Database['public']['Tables']['children']['Insert'];
export type MembershipInsert = Database['public']['Tables']['memberships']['Insert'];
export type EventInsert = Database['public']['Tables']['events']['Insert'];
export type PartyBookingInsert = Database['public']['Tables']['party_bookings']['Insert'];
export type TicketPurchaseInsert = Database['public']['Tables']['ticket_purchases']['Insert'];
export type AppPaymentInsert = Database['public']['Tables']['app_payments']['Insert'];
export type WaiverUserInsert = Database['public']['Tables']['waiver_users']['Insert'];
export type WaiverUserChildInsert = Database['public']['Tables']['waiver_user_children']['Insert'];
export type WaiverSubmissionInsert = Database['public']['Tables']['waiver_submissions']['Insert'];
export type AnnouncementInsert = Database['public']['Tables']['announcements']['Insert'];
export type MembershipPlanInsert = Database['public']['Tables']['membership_plans']['Insert'];
export type EventPhotoInsert = Database['public']['Tables']['event_photos']['Insert'];

// ============= Update types =============
export type UserUpdate = Database['public']['Tables']['users']['Update'];
export type CustomerUpdate = Database['public']['Tables']['customers']['Update'];
export type ChildUpdate = Database['public']['Tables']['children']['Update'];
export type MembershipUpdate = Database['public']['Tables']['memberships']['Update'];
export type EventUpdate = Database['public']['Tables']['events']['Update'];
export type PartyBookingUpdate = Database['public']['Tables']['party_bookings']['Update'];
export type TicketPurchaseUpdate = Database['public']['Tables']['ticket_purchases']['Update'];
export type WaiverUserUpdate = Database['public']['Tables']['waiver_users']['Update'];
export type WaiverSubmissionUpdate = Database['public']['Tables']['waiver_submissions']['Update'];
